#MEAN = 0    #-0.08121
#STD = 1    #0.41141

# BASIC
WANDBPROJECTNAME = 'triplets-timit-simple'
EPOCHS_TOTAL = 9999
# DATASETS & CACHE
DATASET_DIR = "/media/my3bikaht/EXT4/datasets/TIMIT2/datasets/"
DATASET_TRAIN = "glued-2_56s-mel128-plain-train.dt"
DATASET_VALIDATE = "glued-2_56s-mel128-plain-validate.dt"
DATASET_TEST = "TIMIT-test.dt"
SPECTROGRAMS_CACHE = "/media/my3bikaht/EXT4/datasets/TIMIT2/cache/glued-2_56s-mel128-plain"
# VISUALISATION
VIZ_DIR = "./visualization/"
# CHECKPOINTS
CHECKPOINTFILENAME = "./checkpoints/timit_v4_66.7-316.dict"
# SUBSETS
USE_SUBSETS = True
SUBSET_SPEAKERS = 64
SUBSET_SPECTROGRAMS_PER_SPEAKER = 50
# TRIPLETS
MARGIN = .3
BATCH_SIZE = 64
TRIPLETSPERCLASS = 20
POSITIVECRITERION = 'Random'
NEGATIVESEMIHARD = 0
NEGATIVEHARD = 0

# ATTENTION
############ PRIMARY CONSTANTS ##############
# Original input vectors' length (embeddings)
D_MODEL = 80
D_FINAL = 128
D_K = 32
D_V = 32
NUM_HEADS = 8
ATTN_BATCH_SIZE = 64
SEQUENCE_LENGTH = 200
D_FFN_INNER = 2048

################# DROPOUTS ##################
POSITIONAL_ENCODER_DROPOUT = .1
SCALED_DOT_PRODUCT_ATTENTION_DROPOUT = .1
MULTI_HEAD_ATTENTION_DROPOUT = .1
FEED_FORWARD_DROPOUT = .1

############ DOT PRODUCT SCALE ##############
DOT_PRODUCT_SCALE = D_K**2
