general:
  pretrained:
    desc: Path to pretrained model
    value: ./checkpoints/n8hpx2ki038.dict
  checkpoint:
    desc: Checkpoint filename
    value: ./checkpoints/3kbp9k6a014.dict
  classes:
    desc: Number of classes
    value: 630
  gpu_id:
    desc: GPU ID to use
    value: 0
  epochs:
    desc: Max epochs
    value: 200
  batch_size:
    desc: Batch size
    value: 32
  torchinfo_shape:
    desc: Torchinfo shape
    value: [64,1,64,192]

optimizer:
  initial_lr:
    desc: Initial lr
    value: 0.001
  momentum:
    desc: Momentum
    value: 0.9
  weight_decay:
    desc: Weight decay
    value: 0
  nesterov:
    desc: Use Nesterov?
    value: False

scheduler:
  multiplier:
    desc: Multiplier per step
    value: 0.1
  triggers:
    desc: Epochs when to step
    value: [300,400,500]

wandb:
  project: 
    desc: Project name
    value: compare

model:
  name:
    desc: Model name
    value: Janet
  override_classifier:
    desc: Classifier name
    value: Classifier

dataset:
  train:
    file:
      desc: Dataset index, train
      value: /Volumes/EXT4/datasets/TIMIT2/final/train.dt
    dirs:
      desc: Dataset dirs, train
      value: 
        - /Volumes/EXT4/datasets/TIMIT2/final/cache/train
  test:
    file:
      desc: Dataset index, test
      value: /Volumes/EXT4/datasets/TIMIT2/final/test.dt
    dirs:
      desc: Dataset dirs, test
      value: 
        - /Volumes/EXT4/datasets/TIMIT2/final/cache/test
  useindex:
    desc: Use file indexing to speed up localization of the spectrograms 
    value: False

augmentations:
  desc: Augmentations
  # mix, erase, noise, gradclip, label_smoothing
  value:
    - mix
    - erase
    - label_smoothing
  train_mode:
    desc: Single or double training pass (augm and non-augm data)
    value: 1

visualization:
  dir:
    desc: Visualization dir
    value: ./visualization 

triplets:
  margin: 
    desc: Triplets margin
    value: 0.3
  batch_size:
    desc: Triplets batch size
    value: 32
  per_class:
    desc: Triplets per class
    value: 20
  subsets:
    use:
      desc: Use subsets?
      value: True
    speakers:
      desc: Speakers per subset
      value: 64
    spectrograms:
      desc: Spectrograms per speaker
      value: 50
  criterion:
    positive:
      desc: Positive criterion (Random or Hard)
      # When POSITIVECRITERION == 'Hard' closest positive AND farthest
      # negative will be selected not taking into account following
      # negative strategies
      value: Random
    negative:
      semi_hard:
        desc: Use semi-hard negatives
        value: True
      hard:
        desc: Use hard negatives
        value: True
