general:
  pretrained:
    desc: Path to pretrained model
    value: ./checkpoints/n8hpx2ki038.dict
  checkpoint:
    desc: Checkpoint filename
    value: ./checkpoints/1lhkfdg8006.dict
  classes:
    desc: Number of classes
    value: 5994
  gpu_id:
    desc: GPU ID to use
    value: 0
  epochs:
    desc: Max epochs
    value: 2000
  batch_size:
    desc: Batch size
    value: 32
  torchinfo_shape:
    desc: Torchinfo shape
    value: [64,1,64,192]

optimizer:
  initial_lr:
    desc: Initial lr
    value: 0.001
  momentum:
    desc: Momentum
    value: 0.9
  weight_decay:
    desc: Weight decay
    value: 0
  nesterov:
    desc: Use Nesterov?
    value: False

scheduler:
  multiplier:
    desc: Multiplier per step
    value: 0.1
  triggers:
    desc: Epochs when to step
    value: [1000,2000,10000]


wandb:
  project: 
    desc: Project name
    value: compare

model:
  name:
    desc: Model name
    value: Janet
  override_classifier:
    desc: Classifier name
    value: ClassifierEmbeddings

dataset:
  train:
    file:
      desc: Dataset index, train
      value: /mnt/nvme2tb/datasets/voxceleb2/fastrun/filtered-hpf/train.dt
    dirs:
      desc: Dataset dirs, train
      value: 
        - /mnt/nvme2tb/datasets/voxceleb2/fastrun/filtered-hpf/cache/train
        - /mnt/nvme1tb/datasets/voxceleb2/fastrun/filtered-hpf/cache/train
  valid:
    file:
      desc: Dataset index, validate
      value: /mnt/nvme2tb/datasets/voxceleb2/fastrun/filtered-hpf/validate.dt
    dirs:
      desc: Dataset dirs, validate
      value: 
        - /mnt/nvme2tb/datasets/voxceleb2/fastrun/filtered-hpf/cache/validate
        - /mnt/nvme1tb/datasets/voxceleb2/fastrun/filtered-hpf/cache/validate

augmentations:
  desc: Augmentations
  # mix, erase, noise, gradclip, label_smoothing
  value:
    - mix
    - erase
    - label_smoothing

visualization:
  dir:
    desc: Visualization dir
    value: ./visualization 

triplets:
  margin: 
    desc: Triplets margin
    value: 0.3
  batch_size:
    desc: Triplets batch size
    value: 128
  per_class:
    desc: Triplets per class
    value: 20
  subsets:
    use:
      desc: Use subsets?
      value: True
    speakers:
      desc: Speakers per subset
      value: 64
    spectrograms:
      desc: Spectrograms per speaker
      value: 50
  criterion:
    positive:
      desc: Positive criterion (Random or Hard)
      # When POSITIVECRITERION == 'Hard' closest positive AND farthest
      # negative will be selected not taking into account following
      # negative strategies
      value: Random
    negative:
      semi_hard:
        desc: Use semi-hard negatives
        value: True
      hard:
        desc: Use hard negatives
        value: True
